### ISSUE TITLE
Python3 Support

### ISSUE THREAD

**Issue by acrosby** [metocean/wavespectra#15]
Curious where the hurdles to Python 3 support are. Happy to help work around them as since major scientific packages, including xarray, are dropping support for Python 2 going forward.

By modifying the setup.py, I can install the package from source but get "1 failed, 27 passed, 8 warnings, 11 error" out of running the tests. Not sure yet how much of that is my environment/package versions or Python 3 specific.--`.itervalues` on dicts seems to be a common error in the trace though.

Cheers,
Alex

**Comment by rafa-guedes** [comment]
Hi @acrosby @colourcode thanks for that. Supporting python3 is definitely in the roadmap and any help will be welcome. Currently the main hurdle is with compiling the fortran module to install the watershed stuff. @jorgeperezg has coded that module in pure python, the code is currently in the [wshed](https://github.com/metocean/wavespectra/tree/wshed) branch. However the fortran one is considerably faster to run which makes a difference when processing many spectra datasets. We will look into this soon to try to either make the fortran module compile on python3 or to replace that by the python code.

**Comment by rafa-guedes** [comment]
Fixed in #17

**Comment by RubendeBruin** [comment]
scikit-image features a watershed implementation using cython.
[link](https://github.com/scikit-image/scikit-image/tree/master/skimage/morphology)

It may be easier to use that one instead of the fortran code.
