### ISSUE TITLE
Split direction around north

### ISSUE THREAD

**Issue by andreall** [metocean/wavespectra#36]
![image](https://user-images.githubusercontent.com/25382032/116264602-b5a0e000-a77a-11eb-9b35-98b2ba94cf60.png)

I am trying to split spectra on the northern quadrant:
ds.spec.split(dmin=270, dmax=45)
but obtain "{ValueError}dmax needs to be greater than dmin"...is there a way to get this or should I do first 
d1 = ds.spec.split(dmin=270)
d2 = ds.spec.split(dmax=45)
and then concat?

Thanks!

**Comment by jorgeperezg** [comment]
Hi, at the moment is not possible but I just wrote a possible fix and created a pull request in https://github.com/metocean/wavespectra/pull/37

**Comment by andreall** [comment]
Perfect! Thanks!!
