### ISSUE TITLE
PyPI versions appear to be out-of-sync with Release Tags on Github

### ISSUE THREAD

**Issue by acrosby** [metocean/wavespectra#8]
Package versions listed here https://pypi.org/project/wavespectra/ appear to be out of sync with the tags listed https://github.com/metocean/wavespectra/releases. This is confusing since typically release tags are associated with actual versions, but the most recent (within the last few days) updates to both lists have wildly different version numbers. What is the most recent version of the codebase?

**Comment by rafa-guedes** [comment]
Hi @acrosby thanks for your comment - the github versioning started off much earlier than we made the library available via pypi and this is the main reason they are so much out-of-sync. I agree though this is confusing and we will have a look into unifying versioning across these two. For now we have been updating pypi every time there is a new github release so wavespectra 0.2.3 in pypi corresponds to v3.1.3 in github.

**Comment by acrosby** [comment]
@rafa-guedes Thanks for the response, it is good to understand the relationship between the two version numbers until they are maybe reconciled.

**Comment by rafa-guedes** [comment]
@acrosby we have updated pypi version to match the latest github tag. As of now, both are at version `3.1.4`. It is a big jump from `0.2.3` but the github library went over a couple of big restructuring in the last two or three years since it was first designed, hence the major version changes.
